services:
  driver:
    platform: linux/amd64
    image: driver-did-indy
    build:
      context: ..
    ports:
      - "8080:80"
    volumes:
      - "../src/did_indy:/usr/src/app/src/did_indy:z"
      - "./demo.ledgers.toml:/run/secrets/ledgers.toml:z"
    environment:
      ISSUER: "http://driver"
      PASSPHRASE: "insecure-passphrase"
      AUTH: "client-tokens"
      CLIENT_TOKEN_SECRET: "insecure-secret"
      ADMIN_API_KEY: "insecure-api-key"
    command: dev
    healthcheck:
      test: python healthcheck.py localhost 80
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  demo:
    platform: linux/amd64
    image: driver-did-indy
    volumes:
      - "../src:/usr/src/app/src:z"
      - "./main.py:/usr/src/app/main.py:z"
    command: ["python", "main.py"]
    environment:
      DRIVER: http://driver
    depends_on:
      driver:
        condition: service_healthy
