version: '3'
services:

  driver-did-indy:
    platform: linux/amd64
    image: driver-did-indy
    build:
      context: ..
    ports:
      - "8080:80"
    volumes:
      - "../src/driver_did_indy:/usr/src/app/src/driver_did_indy:z"
      - "./demo.ledgers.toml:/usr/src/app/ledgers.toml:z"
    environment:
      DID_INDY_PASSPHRASE: "insecure"
    command: dev
    healthcheck:
      test: python healthcheck.py localhost 80
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  demo:
    platform: linux/amd64
    image: driver-did-indy
    volumes:
      - "../src:/usr/src/app/src:z"
      - "./main.py:/usr/src/app/main.py:z"
    command: ["python", "main.py"]
    environment:
      DRIVER: http://driver-did-indy
    depends_on:
      driver-did-indy:
        condition: service_healthy
