name: Publish Docker container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    if: github.repository_owner == 'Indicio-tech' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/tests.yml

  setup_and_check_publish:
    name: Setup Publish
    runs-on: ubuntu-latest
    outputs:
      commits_today: ${{ steps.commits.outputs.commits_today }}
      date: ${{ steps.date.outputs.date }}
    if: github.repository_owner == 'Indicio-tech' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Print Latest Commit
        run: "echo 'Latest commit: ${{ github.sha }}'"

      - name: Get commits today
        id: commits
        run: echo "commits_today=$(git log --oneline --since='24 hours ago' | wc -l)" >> $GITHUB_OUTPUT

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  publish:
    name: Publish Docker Container
    needs: [tests, setup_and_check_publish]
    # if: needs.setup_and_check_publish.outputs.commits_today > 0 || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/publish.yml
    strategy:
      matrix:
        tag: ["nightly-${{ needs.setup_and_check_publish.outputs.date }}", nightly]
    permissions:
      contents: read
      packages: write
    with:
      tag: ${{ matrix.tag }}