name: Publish did:indy:py Image
run-name: Publish did:indy:py ${{ inputs.tag || github.event.release.tag_name }} Image
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # v2.4.0
        with:
          cache-binary: false
          install: true
          version: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4 # v4.6.0
        with:
          context: .
          file: ./Dockerfile.release
          push: false
          tags: |
            indicio/didindy:${{ inputs.tag || github.event.release.tag_name }}
            indicio/didindy:latest
        env:
          DOCKER_BUILDKIT: 1