name: Publish did:indy:py Image
run-name: Publish did:indy:py ${{ inputs.tag || github.event.release.tag_name }} Image
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-image:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: false
          install: true
          version: latest

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.release
          push: false
          cache-from: type=gha,scope=didindy-py-${{ matrix.arch }}-${{ inputs.tag || github.event.release.tag_name }}
          cache-to: type=gha,scope=didindy-py-${{ matrix.arch }}-${{ inputs.tag || github.event.release.tag_name }},mode=max
          platforms: linux/${{ matrix.arch }}

  publish-images:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache-binary: false
          install: true
          version: latest

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo owner name
        id: lowercase_owner
        run: echo "lowercase_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Setup Image Metadata
        id: image_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ steps.lowercase_owner.outputs.lowercase_owner }}/did-indy-py
          tags: |
            type=raw,value=py${{ matrix.python-version }}-${{ inputs.tag || github.event.release.tag_name }}
          labels: |
            org.opencontainers.image.created=${{ github.event.release.published_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.url=https://github.com/Indicio-tech/did-indy-py
            org.opencontainers.image.source=https://github.com/Indicio-tech/did-indy-py
          annotations: |
            org.opencontainers.image.description=did-indy-py built by https://github.com/Indicio-tech/
            org.opencontainers.image.created=${{ github.event.release.published_at }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.url=https://github.com/Indicio-tech/did-indy-py
            org.opencontainers.image.source=https://github.com/Indicio-tech/did-indy-py

      - name: Publish Docker image to ghcr.io
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile.release
          cache-from: |
            type=gha,scope=didindy-py-arm64-${{ inputs.tag || github.event.release.tag_name }}
            type=gha,scope=didindy-py-amd64-${{ inputs.tag || github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.image_metadata.outputs.tags }}
          labels: ${{ steps.image_metadata.outputs.labels }}
          annotations: ${{ steps.image_metadata.outputs.annotations }}