name: Ruff
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check
          src: "./src ./tests"
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check
          src: "./src ./tests"
